=== CharlieMcFly/Master_1/Semestre 2/LABD/TP5/exercice-2/catalogue.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xsi:schemaLocation="http://www.w3.org/2001/XMLSchema
                         http://www.w3.org/2001/XMLSchema.xsd"
            xmlns="http://labd/art"
            targetNamespace="http://labd/art"
            elementFormDefault="qualified">
            
  <!-- description des oeuvres -->

  <xsd:simpleType name="typeGenreOeuvre">
    <xsd:restriction base="xsd:token">
      <xsd:enumeration value="sculpture"/>
      <xsd:enumeration value="peinture"/>
      <xsd:enumeration value="dessin"/>
      <xsd:enumeration value="autre"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:element name="oeuvre">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="titre" type="xsd:string"/>
        <xsd:element name="auteur">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="nom" type="xsd:string"/>
              <xsd:element name="prénom" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="date" type="xsd:gYear" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute default="peinture" name="genre" type="typeGenreOeuvre"/>
    </xsd:complexType>
  </xsd:element>
  
  <!-- catalogue = 1 musée et des oeuvres -->

  <xsd:element name="catalogue">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="musée" type="xsd:string"/>
        <xsd:element ref="oeuvre" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element> 
    
</xsd:schema>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP5/exercice-2/catalogue-1.xml
<?xml version="1.0" encoding="utf-8"?>
<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://labd/art"
   xsi:schemaLocation="http://labd/art catalogue.xsd">
                         
   <musée>Centre Beaubourg</musée>
   <oeuvre genre="peinture">
     <titre>Les demoiselles d'Avignon</titre>
     <auteur>
       <nom>Picasso</nom>
       <prénom>Pablo</prénom>
     </auteur>
     <date>1907</date>
   </oeuvre>
   <oeuvre genre="peinture">
     <titre>Le Chant du rossignol à minuit et la pluie matinale</titre>
     <auteur>
       <nom>Miro</nom>
       <prénom>Joan</prénom>
     </auteur>
     <date>1940</date>
   </oeuvre>
   <oeuvre genre="peinture">
     <titre>Terre Labourée</titre>
     <auteur>
       <nom>Miro</nom>
       <prénom>Joan</prénom>
     </auteur>
     <date>1924</date>
   </oeuvre>   
   <oeuvre genre="sculpture">
     <titre>Femme et Oiseau</titre>
     <auteur>
       <nom>Miro</nom>
       <prénom>Joan</prénom>
     </auteur>
     <date>1967</date>
   </oeuvre>   
   <oeuvre genre="peinture">
     <titre>L'empire des lumières</titre>
     <auteur>
       <nom>Magritte</nom>
       <prénom>René</prénom>
     </auteur>
     <date>1954</date>
   </oeuvre>  
   <oeuvre genre="peinture">
     <titre>Periscope (Hart Crane)</titre>
     <auteur>
       <nom>Johns</nom>
       <prénom>Jasper</prénom>
     </auteur>
     <date>1963</date>
   </oeuvre>
</catalogue>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP5/exercice-2/catalogue-2.xml
<?xml version="1.0" encoding="utf-8"?>
<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://labd/art"
   xsi:schemaLocation="http://labd/art catalogue.xsd">
   <musée>Musée BDA</musée>
   <oeuvre genre="peinture">
     <titre>Nature morte à la chaise cannée</titre>
     <auteur>
       <nom>Picasso</nom>
       <prénom>Pablo</prénom>
     </auteur>
     <date>1912</date>
   </oeuvre>
   <oeuvre genre="peinture">
     <titre>La trahison des images</titre>
     <auteur>
       <nom>Magritte</nom>
       <prénom>René</prénom>
     </auteur>
     <date>1929</date>
   </oeuvre>  
</catalogue>
