=== CharlieMcFly/Master_1/Semestre 2/LABD/TP3/labd-3/maisons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            
	<xsd:group name="TypeConteneurPieces">
		<xsd:sequence>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="alcove" type="TypePiece"/>
			<xsd:element name="cuisine" type="TypePiece"/>
			<xsd:element name="séjour" type="TypePiece"/>
			<xsd:element name="bureau" type="TypePiece"/>
			<xsd:element name="garage" type="TypePiece"/>
			<xsd:element name="terrasse" type="TypePiece"/>
			<xsd:element name="chambre" type="TypePiece"/>
			<xsd:element name="salledeBain" type="TypePiece"/>
			<xsd:element name="mirador" type="TypePiece"/>
			<xsd:element name="WC" type="TypePiece"/>
		</xsd:choice>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:complexType name="TypeNiveau">
		<xsd:group ref="TypeConteneurPieces"/>
	</xsd:complexType>
	
	<xsd:complexType name="TypePiece" mixed="true">
		<xsd:group ref="TypeConteneurPieces"/>
		<xsd:attribute name="surface-m2" type="xsd:decimal"/>
		<xsd:attribute name="fenetre" type="xsd:positiveInteger"/>
	</xsd:complexType>
	
	
	<xsd:element name="maison">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="étage" type="TypeNiveau"/>
			<xsd:element name="RDC" type="TypeNiveau"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="maisons">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="maison"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP6/labd-6/exercice-2/maisons.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<maisons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="maisons.xsd">
  <maison id="1">
    <RDC>
      <cuisine surface-m2="12">Evier Inox. Mobilier encastre</cuisine>
      <WC>Lavabo.</WC>
      <sejour  surface-m2="38">Cheminee en pierre. Baie vitree</sejour>
      <bureau surface-m2="14">Bibliotheque</bureau>
      <garage/>
    </RDC>
    <etage>
      <terrasse/>
      <chambre surface-m2="28" fenetre="3">
        <alcove surface-m2="8"/>
      </chambre>
      <chambre surface-m2="18"/>
      <salledeBain surface-m2="15">
        Douche, baignoire, lavabo
      </salledeBain>
    </etage>
  </maison>
  <maison id="2">
    <RDC>
      <cuisine surface-m2="12">en ruine</cuisine>
      <garage/>
    </RDC>
    <etage>
      <mirador surface-m2="1">
        Vue sur la mer
      </mirador>
      <salledeBain surface-m2="15">Douche</salledeBain>
    </etage>
  </maison>
  <maison id="3">
    <RDC>
      <sejour fenetre="4" surface-m2="40"/>
    </RDC>
    <etage>
      <chambre surface-m2="17.5">Exposition plein sud</chambre>
    </etage>
  </maison>
</maisons>
