=== CharlieMcFly/Master_1/Semestre 2/LABD/TP7/labd-7/expression.xsd
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.expression.org"
	xmlns="http://www.expression.org"
	elementFormDefault="qualified">
	<xsd:simpleType name="type-operation">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="+"/>
			<xsd:enumeration value="-"/>
			<xsd:enumeration value="*"/>
			<xsd:enumeration value="/"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="type-var">
		<xsd:restriction base="xsd:Name">
			<xsd:pattern value="[A-Z]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:group name="type-expression">
		<xsd:choice>
			<xsd:element name="cons" type="xsd:integer"/>
			<xsd:element name="var" type="type-var"/>
			<xsd:element ref="op"/>
		</xsd:choice>
	</xsd:group>
	<xsd:element name="op">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="type-expression"/>
				<xsd:group ref="type-expression"/>
			</xsd:sequence>
			<xsd:attribute name="val" type="type-operation"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="expr">
		<xsd:complexType>
			<xsd:group ref="type-expression"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP3/labd-3/expression.xml
<?xml version="1.0" encoding="utf-8"?>
<expr xsi:noNamespaceSchemaLocation="expression.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
	<op val="+">
		<var>X</var>
		<op val="-">
			<op val="/"><cons>6</cons><cons>-2</cons></op>
			<var>Y</var>
		</op>
	</op>
</expr>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP7/labd-7/expression2.xml
<?xml version="1.0" encoding="utf-8"?>
<expr xsi:schemaLocation="http://www.expression.org expression.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.expression.org">
	<op val="+">
		<cons>2</cons>
		<op val="-">
			<op val="/"><cons>6</cons><cons>-2</cons></op>
			<cons>4</cons>
		</op>
	</op>
</expr>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP7/labd-7/expression.xml
<?xml version="1.0" encoding="utf-8"?>
<expr xsi:schemaLocation="http://www.expression.org expression.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.expression.org">
	<op val="+">
		<var>X</var>
		<op val="-">
			<op val="/"><cons>6</cons><cons>-2</cons></op>
			<var>Y</var>
		</op>
	</op>
</expr>
