=== CharlieMcFly/Master_1/Semestre 2/LABD/TP1/labd-1/famille.dtd
<!ELEMENT famille (nom, personne+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT personne (prenom, age, (poids-kg|poids-lb), taille?)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT poids-lb (#PCDATA)>
<!ELEMENT poids-kg (#PCDATA)>
<!ELEMENT taille (#PCDATA)>
<!ATTLIST personne pnumber ID #REQUIRED mere IDREF #IMPLIED pere IDREF #IMPLIED>

=== CharlieMcFly/Master_1/Semestre 2/LABD/Workspace/TP1/famille.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE famille SYSTEM "famille.dtd"> 
<famille>
	<nom>Martin</nom>
	<personne pnumber="a1">
		<prenom>Juliette</prenom>
		<age>30</age>
		<poids-kg>58</poids-kg>
	</personne>
	<personne pnumber="a2">
		<prenom>Romeo</prenom>
		<age>31</age>
		<poids-lb>97</poids-lb>
	</personne>
	<personne pnumber="a3" mere="a1" pere="a2">
		<prenom>Max</prenom>
		<age>4</age>
		<poids-kg>12</poids-kg>
		<taille>1.25</taille>
	</personne>
	<personne pnumber="a4" mere="a1" pere="a2">
		<prenom>Marie</prenom>
		<age>3</age>
		<poids-lb>18</poids-lb>
		<taille>1.10</taille>
	</personne>
</famille>
