=== CharlieMcFly/Master_1/Semestre 2/LABD/TP5/exercice-1/championnat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- les clubs -->
  
 
  
  <!-- Le type d'un club -->
  <xsd:complexType name="TypeClub">
    <xsd:sequence>
      <!-- le nom du club -->
      <xsd:element name="nom" type="xsd:string"/>
      <xsd:element name="ville" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID"/>
  </xsd:complexType>
  
  <!-- l'element clubs contient une sequence d'element club -->
  <xsd:element name="clubs">
    <xsd:complexType>
      <xsd:sequence>
       <xsd:element name="club" type="TypeClub" minOccurs="0" maxOccurs="unbounded" />
     </xsd:sequence>
   </xsd:complexType>
   <!-- l'attribut id est une clef pour les clubs -->
   <xsd:key name="clefClub">
     <xsd:selector xpath="club"/>
     <xsd:field xpath="@id"/>
   </xsd:key>
  </xsd:element>
  
  <!-- Les journees -->
  
  <!-- un type pour une rencontre -->
  <xsd:complexType name="TypeRencontre">
    <xsd:sequence>
      <xsd:element name="receveur" type="xsd:IDREF"/>
      <xsd:element name="invite" type="xsd:IDREF"/>
      <xsd:element name="score">
        <xsd:simpleType>
          <xsd:list itemType="xsd:nonNegativeInteger"/>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- un numero de journee est un entier entre 1 et 38 -->
  <xsd:simpleType name="TypeNumJournee">
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:minInclusive value="1"/>
      <xsd:maxInclusive value="38"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <!-- type pour une journee : sequence de rencontres, et attribut numero de la journee -->
  
  <xsd:complexType name="TypeJournee">
    <xsd:sequence>
      <xsd:element name="date" type="xsd:date"/>
      <xsd:element name="rencontre" type="TypeRencontre" minOccurs="1" maxOccurs="10" />
    </xsd:sequence>
    <xsd:attribute name="num" type="TypeNumJournee"/>
  </xsd:complexType>
  
  <!-- pour finir, l'element journees contient une sequence d'elements journee -->
  <xsd:element name="journees">
    <xsd:complexType>
      <xsd:sequence>
       <xsd:element name="journee" type="TypeJournee" minOccurs="0" maxOccurs="38" />
     </xsd:sequence>
   </xsd:complexType>
   <!-- l'attribut num de journee est une clef primaire pour les journees -->
   <xsd:key name="clefJournee">
     <xsd:selector xpath="journee"/>
     <xsd:field xpath="@num"/>
   </xsd:key>
  </xsd:element>
  
  <!-- L'element racine, et les clefs etrangÃ¨res -->
  <xsd:element name="championnat">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="clubs"/>
        <xsd:element ref="journees"/>
      </xsd:sequence>
      <xsd:attribute name="annee" type="xsd:positiveInteger">
      </xsd:attribute>
    </xsd:complexType>
    <xsd:keyref name="refClub1" refer="clefClub">
      <xsd:selector xpath="journees/journee/rencontre"/>
      <xsd:field xpath="receveur"/>
    </xsd:keyref>
    <xsd:keyref name="refClub2" refer="clefClub">
      <xsd:selector xpath="journees/journee/rencontre"/>
      <xsd:field xpath="invite"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>

=== CharlieMcFly/Master_1/Semestre 2/LABD/TP5/exercice-1/championnat.xml
<?xml version="1.0" encoding="utf-8"?>
<championnat xsi:noNamespaceSchemaLocation="championnat.xsd" 
	annee="2015" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<clubs>
		<club id="LOSC">
			<nom>Lille Olympique Sporting Club Lille Metropole</nom>
			<ville>Lille</ville>
		</club>
		<club id="SRFC">
			<nom>Stade Rennais Football Club</nom>
			<ville>Rennes</ville>
		</club>
		<club id="OL">
			<nom>Olympique Lyonnais</nom>
			<ville>Lyon</ville>
		</club>
		<club id="OM">
			<nom>Olympique de Marseille</nom>
			<ville>Marseille</ville>
		</club>
		<club id="PSG">
			<nom>Paris Saint-Germain Football Club</nom>
			<ville>Paris</ville>
		</club>
		<club id="MHSC">
			<nom>Montpellier Herault Sport Club</nom>
			<ville>Montpellier</ville>
		</club>
		<club id="ASSE">
			<nom>Association Sportive de Saint-Etienne</nom>
			<ville>Saint Etienne</ville>
		</club>
		<club id="GB">
			<nom>Girondins de Bordeaux</nom>
			<ville>Bordeaux</ville>
		</club>
		<club id="FCL">
			<nom>Football Club Lorient</nom>
			<ville>Lorient</ville>
		</club>
		<club id="ASMFC">
			<nom>Association sportive Monaco Football Club</nom>
			<ville>Monaco</ville>
		</club>
		<club id="OGCN">
			<nom>Olympique Gymnaste Club Nice Cote d'Azur</nom>
			<ville>Nice</ville>
		</club>
		<club id="SR">
			<nom>Stade de Reims</nom>
			<ville>Reims</ville>
		</club>
		<club id="SCB">
			<nom>Sporting Club de Bastia</nom>
			<ville>Bastia</ville>
		</club>
		<club id="ETGFC">
			<nom>Evian Thonon Gaillard Football Club</nom>
			<ville>Evian</ville>
		</club>
		<club id="EAG">
			<nom>En Avant de Guingamp</nom>
			<ville>Guingamp</ville>
		</club>
		<club id="TFC">
			<nom>Toulouse Football Club</nom>
			<ville>Toulouse</ville>
		</club>
		<club id="FCN">
			<nom>Football Club de Nantes</nom>
			<ville>Nantes</ville>
		</club>
		<club id="SMC">
			<nom>Stade Malherbe Caen</nom>
			<ville>Caen</ville>
		</club>
		<club id="RCL">
			<nom>Racing Club de Lens</nom>
			<ville>Lens</ville>
		</club>
		<club id="FCM">
			<nom>Football Club de Metz</nom>
			<ville>Metz</ville>
		</club>
	</clubs>
	<journees>
		<journee num="1">
			<date>2014-08-09</date>
			<rencontre>
				<receveur>SR</receveur>
				<invite>PSG</invite>
				<score>2 2</score>
			</rencontre>
			<rencontre>
				<receveur>SCB</receveur>
				<invite>OM</invite>
				<score>3 3</score>
			</rencontre>
			<rencontre>
				<receveur>ETGFC</receveur>
				<invite>SMC</invite>
				<score>0 3</score>
			</rencontre>
			<rencontre>
				<receveur>EAG</receveur>
				<invite>ASSE</invite>
				<score>0 2</score>
			</rencontre>
			<rencontre>
				<receveur>LOSC</receveur>
				<invite>FCM</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>MHSC</receveur>
				<invite>GB</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>FCN</receveur>
				<invite>RCL</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>OGCN</receveur>
				<invite>TFC</invite>
				<score>3 2</score>
			</rencontre>
			<rencontre>
				<receveur>OL</receveur>
				<invite>SRFC</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>ASMFC</receveur>
				<invite>FCL</invite>
				<score>1 2</score>
			</rencontre>
		</journee>
		<journee num="2">
			<date>2014-08-16</date>
			<rencontre>
				<receveur>SMC</receveur>
				<invite>LOSC</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>PSG</receveur>
				<invite>SCB</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>RCL</receveur>
				<invite>EAG</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>FCL</receveur>
				<invite>OGCN</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>FCM</receveur>
				<invite>FCN</invite>
				<score>1 1</score>
			</rencontre>
			<rencontre>
				<receveur>SRFC</receveur>
				<invite>ETGFC</invite>
				<score>6 2</score>
			</rencontre>
			<rencontre>
				<receveur>TFC</receveur>
				<invite>OL</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>OM</receveur>
				<invite>MHSC</invite>
				<score>0 2</score>
			</rencontre>
			<rencontre>
				<receveur>ASSE</receveur>
				<invite>SR</invite>
				<score>3 1</score>
			</rencontre>
			<rencontre>
				<receveur>GB</receveur>
				<invite>ASMFC</invite>
				<score>4 1</score>
			</rencontre>
		</journee>
		<journee num="3">
			<date>2014-08-23</date>
			<rencontre>
				<receveur>ETGFC</receveur>
				<invite>PSG</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>EAG</receveur>
				<invite>OM</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>SCB</receveur>
				<invite>TFC</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>LOSC</receveur>
				<invite>FCL</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>MHSC</receveur>
				<invite>FCM</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>OGCN</receveur>
				<invite>GB</invite>
				<score>1 3</score>
			</rencontre>
			<rencontre>
				<receveur>SR</receveur>
				<invite>SMC</invite>
				<score>0 2</score>
			</rencontre>
			<rencontre>
				<receveur>OL</receveur>
				<invite>RCL</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>ASSE</receveur>
				<invite>SRFC</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>FCN</receveur>
				<invite>ASMFC</invite>
				<score>0 1</score>
			</rencontre>
		</journee>
		<journee num="4">
			<date>2014-08-30</date>
			<rencontre>
				<receveur>OM</receveur>
				<invite>OGCN</invite>
				<score>4 0</score>
			</rencontre>
			<rencontre>
				<receveur>ASMFC</receveur>
				<invite>LOSC</invite>
				<score>1 1</score>
			</rencontre>
			<rencontre>
				<receveur>SMC</receveur>
				<invite>SRFC</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>RCL</receveur>
				<invite>SR</invite>
				<score>4 2</score>
			</rencontre>
			<rencontre>
				<receveur>FCL</receveur>
				<invite>EAG</invite>
				<score>4 0</score>
			</rencontre>
			<rencontre>
				<receveur>FCN</receveur>
				<invite>MHSC</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>TFC</receveur>
				<invite>ETGFC</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>GB</receveur>
				<invite>SCB</invite>
				<score>1 1</score>
			</rencontre>
			<rencontre>
				<receveur>FCM</receveur>
				<invite>OL</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>PSG</receveur>
				<invite>ASSE</invite>
				<score>5 0</score>
			</rencontre>
		</journee>
		<journee num="5">
			<date>2014-09-13</date>
			<rencontre>
				<receveur>OL</receveur>
				<invite>ASMFC</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>SRFC</receveur>
				<invite>PSG</invite>
				<score>1 1</score>
			</rencontre>
			<rencontre>
				<receveur>SCB</receveur>
				<invite>RCL</invite>
				<score>1 1</score>
			</rencontre>
			<rencontre>
				<receveur>MHSC</receveur>
				<invite>FCL</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>OGCN</receveur>
				<invite>FCM</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>SR</receveur>
				<invite>TFC</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>ASSE</receveur>
				<invite>SMC</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>LOSC</receveur>
				<invite>FCN</invite>
				<score>2 0</score>
			</rencontre>
			<rencontre>
				<receveur>EAG</receveur>
				<invite>GB</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>ETGFC</receveur>
				<invite>OM</invite>
				<score>1 3</score>
			</rencontre>
		</journee>
		<journee num="6">
			<date>2014-09-20</date>
			<rencontre>
				<receveur>GB</receveur>
				<invite>ETGFC</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>OM</receveur>
				<invite>SRFC</invite>
				<score>3 0</score>
			</rencontre>
			<rencontre>
				<receveur>FCL</receveur>
				<invite>SR</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>FCM</receveur>
				<invite>SCB</invite>
				<score>3 1</score>
			</rencontre>
			<rencontre>
				<receveur>FCN</receveur>
				<invite>OGCN</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>TFC</receveur>
				<invite>SMC</invite>
				<score>3 3</score>
			</rencontre>
			<rencontre>
				<receveur>LOSC</receveur>
				<invite>MHSC</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>RCL</receveur>
				<invite>ASSE</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>ASMFC</receveur>
				<invite>EAG</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>PSG</receveur>
				<invite>OL</invite>
				<score>1 1</score>
			</rencontre>
		</journee>
		<journee num="7">
			<date>2014-09-24</date>
			<rencontre>
				<receveur>SR</receveur>
				<invite>OM</invite>
				<score>0 5</score>
			</rencontre>
			<rencontre>
				<receveur>SRFC</receveur>
				<invite>TFC</invite>
				<score>0 3</score>
			</rencontre>
			<rencontre>
				<receveur>SCB</receveur>
				<invite>FCN</invite>
				<score>0 0</score>
			</rencontre>
			<rencontre>
				<receveur>ETGFC</receveur>
				<invite>RCL</invite>
				<score>2 1</score>
			</rencontre>
			<rencontre>
				<receveur>EAG</receveur>
				<invite>FCM</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>OL</receveur>
				<invite>FCL</invite>
				<score>4 0</score>
			</rencontre>
			<rencontre>
				<receveur>MHSC</receveur>
				<invite>ASMFC</invite>
				<score>0 1</score>
			</rencontre>
			<rencontre>
				<receveur>OGCN</receveur>
				<invite>LOSC</invite>
				<score>1 0</score>
			</rencontre>
			<rencontre>
				<receveur>SMC</receveur>
				<invite>PSG</invite>
				<score>0 2</score>
			</rencontre>
